const SOCKET_NEW_USER_CONNECTED = 'USER_CONNECTED';
const SOCKET_USER_DISCONNECTED = 'USER_DISCONNECTED';
const SOCKET_USERS = 'USERS';
const SOCKET_PRIVATE_MESSAGE = 'PRIVATE_MESSAGE';
const SOCKET_USER_IS_TYPING = 'USER_IS_TYPING';

// game
const SOCKET_GAME_COMMAND = 'SOCKET_GAME_COMMAND';
const SOCKET_GAME_COMMAND_ENEMY = 'SOCKET_GAME_COMMAND_ENEMY';
const SOCKET_GAME_NEW_GAME_CREATED = 'SOCKET_GAME_NEW_GAME_CREATED';
const SOCKET_GAME_CREATE_NEW_GAME = 'SOCKET_GAME_CREATE_NEW_GAME';
const SOCKET_GAME_USER_CONNECTED = 'SOCKET_GAME_USER_CONNECTED';

// base
const SOCKET_CONNECTION = 'connection';
const SOCKET_DISCONNECT = 'disconnect';
const SOCKET_SESSION_STARTED = 'SESSION';

module.exports = {
  SOCKET_NEW_USER_CONNECTED,
  SOCKET_USER_DISCONNECTED,
  SOCKET_SESSION_STARTED,
  SOCKET_PRIVATE_MESSAGE,
  SOCKET_CONNECTION,
  SOCKET_DISCONNECT,
  SOCKET_USERS,
  SOCKET_USER_IS_TYPING,
  SOCKET_GAME_COMMAND,
  SOCKET_GAME_NEW_GAME_CREATED,
  SOCKET_GAME_CREATE_NEW_GAME,
  SOCKET_GAME_USER_CONNECTED,
  SOCKET_GAME_COMMAND_ENEMY,
};
