const SOCKET_NEW_USER_CONNECTED = 'USER_CONNECTED';
const SOCKET_USER_DISCONNECTED = 'USER_DISCONNECTED';
const SOCKET_USERS = 'USERS';
const SOCKET_SESSION_STARTED = 'SESSION';
const SOCKET_PRIVATE_MESSAGE = 'PRIVATE_MESSAGE';
const SOCKET_GAME_COMMAND = 'SOCKET_GAME_COMMAND';
const SOCKET_CONNECTION = 'connection';
const SOCKET_DISCONNECT = 'disconnect';
const SOCKET_USER_IS_TYPING = 'USER_IS_TYPING';

module.exports = {
  SOCKET_NEW_USER_CONNECTED,
  SOCKET_USER_DISCONNECTED,
  SOCKET_SESSION_STARTED,
  SOCKET_PRIVATE_MESSAGE,
  SOCKET_CONNECTION,
  SOCKET_DISCONNECT,
  SOCKET_USERS,
  SOCKET_USER_IS_TYPING,
  SOCKET_GAME_COMMAND,
};
